CREATE DATABASE BibliotecaDB;

USE BibliotecaDB;

CREATE TABLE Livro (
	id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Titulo NVARCHAR(100) NOT NULL,
	ISBN NVARCHAR(20) NOT NULL,
	idEditora INT NOT NULL
)

CREATE TABLE Editora (
	idEditora INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Nome NVARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL
)

CREATE TABLE Autor (
	idAutor INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Nome NVARCHAR(100) NOT NULL
)

CREATE TABLE Categoria (
	idCategoria INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Nome NVARCHAR(100) NOT NULL
)

CREATE TABLE Exemplar(
	idExemplar INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	idLivro INT NOT NULL,
	Quantidade INT NOT NULL
)

CREATE TABLE Usuario (
	idUsuario INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Nome NVARCHAR(100) NOT NULL,
	Email NVARCHAR(20),
	CPF NVARCHAR(11) NOT NULL,
	Telefone NVARCHAR(11),
	DataCadastro DATETIME DEFAULT GETDATE(),
	Situacao BIT NOT NULL
)

CREATE TABLE Professor(
	idProfessor INT PRIMARY KEY IDENTITY(1,1) NOT NULL, 
	idUsuario INT NOT NULL,
	RP INT NOT NULL --DEFAULT NEWGUID()
)

CREATE TABLE Aluno(
	idAluno INT PRIMARY KEY IDENTITY(1,1) NOT NULL, 
	idUsuario INT NOT NULL,
	RA INT NOT NULL
)

CREATE TABLE AutorLivro (
	id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	idAutor INT NOT NULL,
	idLivro INT NOT NULL
)

CREATE TABLE LivroCategoria (
	id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	idLivro INT NOT NULL,
	idCategoria INT NOT NULL
)

CREATE TABLE Emprestimo (
	id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DataEmprestimo DATETIME NOT NULL DEFAULT GETDATE(),
	idUsuario INT NOT NULL,
	idLivro INT NOT NULL, 
	DataDevolucao DATETIME,
	DataDevolucaoPrevista DATETIME DEFAULT GETDATE()+7	
)

CREATE TABLE Reserva (
	id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	idLivro INT NOT NULL, 
	idUsuario INT NOT NULL,
	DataReserva DATETIME NOT NULL DEFAULT GETDATE(),
	PrevisaoDevolucao DATETIME NOT NULL
)
