CREATE TABLE Clinicas (
	ClinicaID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	NomeFantasia VARCHAR(255) NOT NULL,
	CNPJ VARCHAR(255) NOT NULL UNIQUE,
	EnderecoID INTEGER,
	TelefoneContato VARCHAR(255),
	EmailContato VARCHAR(255),
	PRIMARY KEY(ClinicaID)
);


create table Enderecos (
	EnderecoID INTEGER not null unique generated by default as identity,
	Logradouro VARCHAR(255) not null,
	Numero INTEGER not null,
	Bairro VARCHAR(255) not null,
	CEP VARCHAR(255) not null,
	Cidade VARCHAR(255) not null,
	Estado VARCHAR(2) not null
	PRIMARY KEY(EnderecoID)
)

CREATE TABLE Pacientes (
	PacienteID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	NomeCompleto VARCHAR(255) NOT NULL,
	DataNascimento DATE NOT NULL,
	CPF VARCHAR(255) NOT NULL UNIQUE,
	Telefone VARCHAR(255),
	Email VARCHAR(255),
	NomeContatoEmergencia VARCHAR(255) NOT NULL,
	TelefoneContatoEmergencia VARCHAR(255) NOT NULL,
	PRIMARY KEY(PacienteID)
);

CREATE TABLE Funcionarios (
	FuncionarioID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	NomeCompleto VARCHAR(255) NOT NULL,
	CPF VARCHAR(255) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL,
	Cargo VARCHAR(255) NOT NULL,
	ClinicaID INTEGER NOT NULL,
	Ativo BIT(1) NOT NULL,
	PRIMARY KEY(FuncionarioID)
);

CREATE TABLE Medicos (
	MedicoID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	Especialidade VARCHAR(255) NOT NULL,
	NumeroCRM BIGINT NOT NULL,
	FuncionarioID INTEGER NOT NULL,
	PRIMARY KEY(MedicoID)
);

CREATE TABLE Agendamentos (
	AgendamentoID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	PacienteID INTEGER NOT NULL,
	MedicoID INTEGER NOT NULL,
	ClinicaID INTEGER NOT NULL,
	DataHoraConsulta DATE NOT NULL,
	StatusConsulta VARCHAR(255) NOT NULL,
	PRIMARY KEY(AgendamentoID)
);

CREATE TABLE Prontuarios (
	ProntuarioID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	AgendamentoID INTEGER NOT NULL,
	PacienteID INTEGER NOT NULL,
	HistoricoDoenca VARCHAR(255),
	Diagnostico VARCHAR(255) NOT NULL,
	PrescricaoMedicamentos VARCHAR(255),
	Observacoes VARCHAR(255),
	PRIMARY KEY(ProntuarioID)
);

CREATE TABLE Pagamentos (
	PagamentoID INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	AgendamentoID INTEGER NOT NULL,
	ValorConsulta DECIMAL NOT NULL,
	MeioPagamento VARCHAR(255),
	DataPagamento DATE,
	StatusPagamento VARCHAR(255) NOT NULL,
	PRIMARY KEY(PagamentoID)
);


alter table clinicas
add foreign key(EnderecoID) references Enderecos(EnderecoId)
on update no action on delete no action;  

ALTER TABLE Funcionarios
ADD FOREIGN KEY(ClinicaID) REFERENCES Clinicas(ClinicaID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Agendamentos
ADD FOREIGN KEY(PacienteID) REFERENCES Pacientes(PacienteID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Agendamentos
ADD FOREIGN KEY(MedicoID) REFERENCES Medicos(MedicoID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Agendamentos
ADD FOREIGN KEY(ClinicaID) REFERENCES Clinicas(ClinicaID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Medicos
ADD FOREIGN KEY(FuncionarioID) REFERENCES Funcionarios(FuncionarioID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Prontuarios
ADD FOREIGN KEY(AgendamentoID) REFERENCES Agendamentos(AgendamentoID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Prontuarios
ADD FOREIGN KEY(PacienteID) REFERENCES Pacientes(PacienteID)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Pagamentos
ADD FOREIGN KEY(AgendamentoID) REFERENCES Agendamentos(AgendamentoID)
ON UPDATE NO ACTION ON DELETE NO ACTION;